### ISSUE TITLE
YouTube Links

### ISSUE THREAD

**Issue by sugaratias** [kdeldycke/plumage#10] opened 2014-09-25 15:26 UTC
Hi there, 

I am embedding a YouTube with the `pelican_youtube plugin`.  Despite specifying the width and height of the video in the `.rst` file, the video is huge, and takes up the width of the page. 

 Many thanks

**Comment by kdeldycke** [comment] 2017-01-05 17:09
Can you try to reproduce this issue with the latest version of the theme?

**Comment by kdeldycke** [comment] 2020-08-11 23:18
There is no evidence of the bug being reproduced since 2014. We can close this issue.

**Closed by kdeldycke** 2020-08-11 23:18 UTC
Labels: bug
